export const COLORS = {
	bg_Colour: '#EBEFF3',
	white: '#fff',
	black: '#000',
	text_title: '#2A2A2A',
	text_desc: '#716F6F',
	blue_01: '#0022FF',
	blue_02: '#5585FF',
	light_blue: '#7B00FF',
	purple_01: '#A32AF3',
	purple_02: '#B200FF',
	light_green: '#11A21E',
	light_green_01: '#18BABA',
	light_green_02: '#38D2DC',
	light_green_03: '#6AE1B7',
	light_red: '#C63028',
	light_orange: '#E67123',
	light_pink: '#DF23E6',
    shadow_01: '#BDC2C7BF',
};

export const FONTS = {
	heading_01: {
		fontFamily: 'Quicksand',
		fontWeight: 700,
		fontSize: '28px',
		color: COLORS.text_title,
	},
	heading_02: {
		fontFamily: 'Quicksand',
		fontWeight: 700,
		fontSize: '20px',
		color: COLORS.text_title,
	},
	heading_03: {
		fontFamily: 'Quicksand',
		fontWeight: 700,
		fontSize: '20px',
		color: COLORS.text_desc,
	},
	heading_04: {
		fontFamily: 'Quicksand',
		fontWeight: 700,
		fontSize: '18px',
		color: COLORS.text_title,
	},
	heading_05: {
		fontFamily: 'Quicksand',
		fontWeight: 700,
		fontSize: '16px',
		color: COLORS.text_title,
	},
	heading_06: {
		fontFamily: 'Quicksand',
		fontWeight: 600,
		fontSize: '16px',
		color: COLORS.text_desc,
	},
	para_01: {
		fontFamily: 'Quicksand',
		fontWeight: 500,
		color: COLORS.text_desc,
		fontSize: '12px',
		lineHeight: '24px',
	},
	para_02: {
		fontFamily: 'Quicksand',
		fontWeight: 500,
		color: COLORS.text_title,
		fontSize: '12px',
		lineHeight: '24px',
	},
};
